edition = "2021"
max_width = 100
tab_spaces = 4
reorder_imports = true
match_block_trailing_comma = true
use_small_heuristics = "Default"
newline_style = "Native"
use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "Module"
