[package]
name = "oldwin-platform-vc-ltl5-x86-vista"
description = "OldWin VC-LTL5 library for Windows Vista"
version = "0.1.1+5.2.1-Beta1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license-file.workspace = true
