[package]
name = "oldwin-platform-vc-ltl5-x86-xp-part1"
description = "Part1 of OldWin VC-LTL5 library for Windows xp"
version = "0.1.1+5.2.1-Beta1"
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license-file.workspace = true
